pipeline{
    agent{
        label "single-node"
    }
    stages{
        stage("Deploy"){
            steps{
                sh(
                    script: '''
                        chown -R luongvn. . 
                        cd frontend
                        sudo su luongvn -c "nohup python -m http.server 5500 --bind 0.0.0.0 > nohup-fe.out 2>&1 &"
                    '''
                )
            }
        }
    }
}