pipeline {
    agent {
        label 'single-node'
    }

    stages {
        stage('Build') {
            when {
                changeset "backend/**"
            }
            steps {
                sh(
                    script: 
                    '''
                        cd backend/app
                        pip install -r requirements.txt
                    ''', label: "Build stage"
                )
            }
        }

        stage('Deploy') {
            when {
                changeset "backend/**"
            } 
            steps {
                sh(
                    script: 
                    '''
                        cd backend
                        python -m app.main:app --host 0.0.0.0 --port 8000 --reload 
                    ''', label: "Deploy Stage"
                )
            }
        }
    }
}