pipeline {
    agent {
        label 'single-node'
    }

    stages {
        stage('Build') {
            steps {
                sh(
                    script: '''
                        cd backend

                        python3.12 -m venv .venv
                        . .venv/bin/activate

                        python -m pip install --upgrade pip
                        pip install -r app/requirements.txt

                        python --version
                        python -m uvicorn --version
                    ''',
                    label: "Build stage"
                )
            }
        }

        stage('Deploy') {
            steps {
                sh(
                    script: '''
                        cd backend

                        . .venv/bin/activate

                        python -m uvicorn app.main:app \
                            --host 0.0.0.0 \
                            --port 8000
                    ''',
                    label: "Deploy Stage"
                )
            }
        }
    }
}